// src/lib/cfgGenerator.ts
// Pure function — no React imports, no side effects
import type { ConfigState, BindAction } from '@/types/config';
import { DEPRECATED_CS2_COMMANDS } from '@/lib/constants/deprecatedCmds';

// CS2 bind action → console command mapping
const BIND_COMMAND: Record<BindAction, string> = {
  jump: '+jump',
  duck: '+duck',
  attack: '+attack',
  attack2: '+attack2',
  use: '+use',
  reload: '+reload',
  inspect: '+inspect_weapon',
  scoreboard: '+showscores',
  voiceChat: '+voicerecord',
  buyMenu: 'buymenu',
  grenadeFlash: 'slot7',
  grenadeMolotov: 'slot10',
  grenadeSmoke: 'slot8',
  grenadeHE: 'slot6',
  grenadeDecoy: 'slot9',
};

export function cfgGenerator(state: ConfigState): string {
  const lines: string[] = [
    '// Generated by CS2 Setup Builder',
    '// autoexec.cfg',
    '',
    '// Mouse',
    `sensitivity ${state.mouse.sensitivity}`,
    '',
    '// Audio',
    `volume ${state.audio.masterVolume}`,
    `voice_scale ${state.audio.voiceVolume}`,
    `voice_enable ${state.audio.muteEnemyVoice ? '0' : '1'}`,
    '',
    '// Key Binds',
  ];

  // Emit bind commands
  for (const [action, key] of Object.entries(state.binds) as [BindAction, string][]) {
    const cmd = BIND_COMMAND[action];
    if (cmd) {
      lines.push(`bind "${key}" "${cmd}"`);
    }
  }

  // Add host_writeconfig to persist settings
  lines.push('');
  lines.push('host_writeconfig');

  const output = lines.join('\n');

  // Runtime safety check — ensure no deprecated commands slipped in
  // (this is a development guard; the unit test provides the real assertion)
  // Uses word-boundary regex to avoid matching substrings (e.g. "rate" inside "Generated")
  // import.meta.env.DEV is the Vite-native equivalent of NODE_ENV !== 'production'
  if (import.meta.env.DEV) {
    for (const cmd of DEPRECATED_CS2_COMMANDS) {
      if (new RegExp(`(?<![\\w_])${cmd}(?![\\w_])`).test(output)) {
        console.error(`cfgGenerator: deprecated command found in output: ${cmd}`);
      }
    }
  }

  return output;
}
